AllCops:
  NewCops: enable
  Exclude:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"

  DisplayCopNames: true

Layout/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 66
Metrics/AbcSize:
  
Metrics/ParameterLists:
  Max: 9
Metrics/ModuleLength:
  Max: 137
Metrics/PerceivedComplexity:
  Max: 23
Metrics/CyclomaticComplexity:
  Max: 21
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  IgnoredMethods: ['describe']
  Max: 57


Style/Documentation:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/ClassVars:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Lint/MissingSuper:
  Enabled: false
Lint/ToEnumArguments:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false